### ISSUE TITLE
MX-Cleanup does not work properly

### ISSUE THREAD

**Issue by 3DComputerGraphics** [MX-Linux/mx-cleanup#11]
Dear madams or sirs,

for some time now, MX Cleanup has displayed a certain amount of data after cleaning up (e.g. 43 MB). If you start MX Cleanup again, the same amount of cleaned data (in this case 43 MB) is displayed again and again. I used to get the display 0MB after a single cleanup.

How can I fix this error?

Thank you very much!

![Bildschirmfoto_2024-04-16_14-22-36_01](https://github.com/MX-Linux/mx-cleanup/assets/6830241/ae208768-f894-4426-8569-69475088dc5a)

Debian GNU/Linux 11 (bullseye) (MX Linux)
Intel(R) Core(TM)i7-4600U CPU @ 2.10 GHz
Thinkpad T440s, 12 GB RAM
Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)

**Comment by AdrianTM** [comment]
Thanks for the report, I think I was able to fix it. Update coming though repos shortly.

**Comment by 3DComputerGraphics** [comment]
Dear Adrian,

thanks for your reply. Today there was an update in the repo. Now MX-Cleanup works again perfectly.

Have a nice day!

Best regards
who
