### ISSUE TITLE
Cronjob clears cache of running applications

### ISSUE THREAD

**Issue by introt** [MX-Linux/mx-cleanup#5]
Greetings,

As per the title, the cronjob created by this application clears the cache regardless of whether it is currently in use by applications, resulting in cryptic error messages that literally take years to debug (case in point: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1327).

If you want to delete the cache periodically, do it eg. on login or shutdown; not while other applications are running.

https://github.com/MX-Linux/mx-cleanup/blob/8b405d7e00d791f2b802641d2ec58a779ba7af3f/mainwindow.cpp#L374

Thanks for your consideration.

**Comment by AdrianTM** [comment]
Not everybody runs programs that break if the cache is cleaned. I've haven't had problems in my tests. You also don't HAVE TO clean the cache if that's something the programs you use rely on.

However, the suggestion about running the cleanup at reboot is good, I added an option to run at the cleanup script at reboot in addition to daily/weekly/monthly options.

**Comment by introt** [comment]
The problem with your approach is that users running such programs may not be aware of the consequences, as is the case in the linked issue. Given the popularity of MX Linux, I'd wager that might apply to a sizeable group of people. I hope you reconsider your stance on this; either warning the user of the possibility of inducing instability **prior to opting in**/saving the settings, or only deleting files that haven't been accessed/modified eg. since last boot would go a long way.

You're welcome! Cron's `@reboot` [might prove problematic](https://unix.stackexchange.com/questions/109804/crontabs-reboot-only-works-for-root/109805#109805) esp. with more complicated (filesystem) setups - perhaps something like session triggers could be used instead.

**Comment by AdrianTM** [comment]
Another great suggestion, thanks, I think access time can be used by default without having to pop up too many disclaimers and warnings. Right now I find the files to delete with 'find... -ctime +7' I could simply do 'find... -ctime +7 -atime +7'

**Comment by AdrianTM** [comment]
Thanks again for the great suggestion, I will use atime to make sure the files are not access at the time of deletion
